import React, {useState} from "react";
import { Link, useNavigate } from "react-router-dom";
import "./hiringform.css";
import axios from "axios";

export default function hiringform() {
  const navigate = useNavigate();
  const [companyname, setCompanyName] = useState("");
  const [jobdescription, setJobDescription] = useState("");

  const login = async (e) => {
    e.preventDefault();
    const input = {
      companyname,
      jobdescription
    };
    try{
      const res = await axios.post("http://localhost:3001/hiringform", input);
      if(res.status === 200) navigate("/homecompany");
      console.log(res);
    }
    catch(err){
      console.log(err);
    }
  };

  return(
    <div className="hiringform">
        <form>
        <div className="container">
          <h1>Hiring form to be generated by the company to hire employees</h1>
          <p>This website is only for Small-Scale companies that are to be benefited.</p>
          <p>Please adhere to the Terms & Conditions of our website.</p>
      
          <label htmlFor="companyname"><b>Company Name</b></label>
          <input type="text" placeholder="Enter the Company Name" name="companyname" id="companyname" onChange={e => setCompanyName(e.target.value)} required />
      
          <label htmlFor="jobdescription"><b>Job Description</b></label>
          <input type="text" placeholder="Provide a short description about the roles being offered" name="jobdesc" id="jobdesc" onChange={e => setJobDescription(e.target.value)} required />
    
      
          <button type="submit" className="hirebtn" onClick={hire}>Hire</button>
          <button type="submit" className="cancelbtn" >Cancel</button>
        </div>
      
        <div className="container signin">
          <p>Don't have an account? <Link to="/registercompany">Sign up</Link></p>
          <p>One of the small scale companies? <Link to="/logincompany">Sign in for a company</Link></p>
        </div>
      </form>
    </div>
  );
}
